Bav/add unit tests
eduNEXT/platform-plugin-forum-email-notifier pull request #11
Opened 2023-11-21 21:55 UTC by BryanttV

**Merge checklist:**
Check off if complete *or* not applicable:
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Fixup commits are squashed away
- [ ] Unit tests added/updated
- [ ] Manual testing instructions provided
- [ ] Noted any: Concerns, dependencies, migration issues, deadlines, tickets

2023-11-22 18:55 UTC, Ian2012 commented
@BryanttV Please omit settings files and add tests for forum_digest command

2023-11-22 18:56 UTC, Ian2012 requested changes
@BryanttV Please omit settings files and add tests for the `forum_digest` command

2023-11-22 20:30 UTC, mariajgrimaldi commented on platform_plugin_forum_email_notifier/tests/test_filters.py
> +module_path = "platform_plugin_forum_email_notifier.extensions.filters"
```suggestion
FILTERS_MODULE_PATH = "platform_plugin_forum_email_notifier.extensions.filters"
```

2023-11-22 20:31 UTC, mariajgrimaldi commented on platform_plugin_forum_email_notifier/tests/test_filters.py
> +        self.assertEqual(len(result["context"]["sections"]), 1)
how do we know this section is the instructor tab one?

2023-11-22 20:32 UTC, mariajgrimaldi commented on platform_plugin_forum_email_notifier/tests/test_filters.py
> +        self.assertEqual(len(result["context"]["sections"]), 1)
Same here

2023-11-22 20:37 UTC, mariajgrimaldi commented on platform_plugin_forum_email_notifier/tests/test_tasks.py
> +module_path = "platform_plugin_forum_email_notifier.tasks"
TASKS_MODULE_PATH

2023-11-22 20:38 UTC, mariajgrimaldi commented on platform_plugin_forum_email_notifier/tests/test_tasks.py
> +            recipient=Recipient(1, "test@user-email.com"),
```suggestion
            recipient=Recipient(mock_user.id, mock_user.email),
```

2023-11-22 20:47 UTC, mariajgrimaldi commented on platform_plugin_forum_email_notifier/tests/test_tasks.py
> +        Check `send_email_notification` when user exists.
Can we elaborate a bit more?

2023-11-22 20:48 UTC, mariajgrimaldi commented on platform_plugin_forum_email_notifier/tests/test_tasks.py
> +        Check `send_email_notification` when user does not exist.
If we're gonna use `Check...` let's add `Check send_email_notification behavior...`

2023-11-22 20:50 UTC, mariajgrimaldi commented on platform_plugin_forum_email_notifier/tests/test_tasks.py
> +    def test_send_email_notification_post_does_not_have_title(
can we use ddt?

2023-11-22 20:51 UTC, mariajgrimaldi commented on platform_plugin_forum_email_notifier/tests/test_tasks.py
> +        mock_handle_digests.assert_called()
can we check the arguments are correct?

2023-11-22 20:52 UTC, mariajgrimaldi commented on platform_plugin_forum_email_notifier/tests/test_tasks.py
> +
```suggestion
```

2023-11-22 20:53 UTC, mariajgrimaldi approved these changes
LGTM. Just a few comments left to address

2023-11-23 13:35 UTC, Ian2012 approved these changes

2023-11-23 15:40 UTC, merged